version: '3.8'

services:
  postgres:
    image: postgres:18
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    ports:
      - "5435:5435"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: spring_app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    env_file:
      - .env

volumes:
  postgres_data: