spring:
  application:
    name: bookstoreapp
  config:
    import: optional:file:.env[.properties]
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 5MB
        
        
  datasource:
    url: jdbc:postgresql://localhost:5432/bookstore
    username: postgres
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
      hibernate:
        ddl-auto: update  # create, update, validate, none
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
          jdbc:
            batch_size: 20
      open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: "*"

jwt:
  secret: ${JWT_SECRET}
  access-expiration: 900000      # 15 min (in ms)
  refresh-expiration: 604800000  # 7 days (in ms)

cors:
  allowedUrl: ${ALLOWED_URL}

cloud:
  aws:
    bucket:
      name: ${S3_BUCKET_NAME}
    credentials:
      access-key: ${AWS_S3_ACCESS_KEY}
      secret-key: ${AWS_S3_SECRET_KEY}
    region:
      static: ${AWS_S3_REGION}